### ISSUE TITLE
Issue with oncreateview option in fragments viewpager

### ISSUE THREAD

**Issue by veerastha** [AtomicSpider/Tinder-Like-Action-Bar#1]
thanks for code but there is major issue i.e oncreateview of tab2 is automatically getting called when app is launched along with tab1 and when swiped to second fragment then tab3's oncreateview is called so please give a solution to this bug..

**Comment by AtomicSpider** [comment]
Hi,
This is not a bug. When you use viewpager, it automatically loads adjacent fragments. How many adjacent fragments to load, that can be controlled using mViewPager.setOffscreenPageLimit(x);
But there is no way to load just the current fragment because the minimum is one.

There is a workaround to this though. You can add this code to your fragment. This will only execute when the fragment is visible.

@Override
    public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);

        if (isVisibleToUser) {
            Log.i("Fragment is visible");
            //ToDo
        }
    }

**Comment by veerastha** [comment]
thankyou so much @AtomicSpider for such fast reply... sorry that i was not aware of that piece of information and once again thanks for the code helped me alot...
